# Generated by Django 4.2.1 on 2023-08-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='senha',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='pontos'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
