# Generated by Django 4.2.1 on 2023-08-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
