# Generated by Django 4.2.1 on 2023-08-18 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cc',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='pontos'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
