# Generated by Django 4.2.1 on 2023-08-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_customuser_cc_alter_customuser_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_rh',
            field=models.BooleanField(default=False),
        ),
    ]
