# Generated by Django 4.2.1 on 2023-08-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
