# Generated by Django 4.2.4 on 2024-03-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_requests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manager_points',
            field=models.PositiveIntegerField(default=0, verbose_name='manager_points'),
        ),
    ]
