# Generated by Django 4.2.4 on 2024-03-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_customuser_manager_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='quantidade',
            field=models.PositiveIntegerField(default=False, verbose_name='quantidade'),
        ),
    ]
