# Generated by Django 4.2.4 on 2024-03-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_requests_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(choices=[(50, '50'), (100, '100'), (150, '150'), (200, '200')]),
        ),
    ]
